# Generated by Django 4.2.19 on 2025-02-19 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250, verbose_name='Вопрос')),
                ('answer1', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ответ1')),
                ('answer2', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ответ2')),
                ('answer3', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ответ3')),
                ('answer4', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ответ4')),
                ('status', models.IntegerField(blank=True, null=True, verbose_name='Статус ответа')),
                ('message', models.CharField(blank=True, max_length=250, null=True, verbose_name='Сообщение')),
                ('role', models.CharField(default='user', max_length=50, verbose_name='Роль')),
            ],
        ),
    ]
