# Generated by Django 4.2.19 on 2025-02-19 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userQuiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='role',
        ),
    ]
