# Generated by Django 4.2.19 on 2025-02-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userQuiz', '0002_remove_quiz_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='answerCorrect',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Правильный'),
        ),
    ]
