# Generated by Django 5.1.6 on 2025-02-24 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userQuiz', '0003_quiz_answercorrect'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='answerUser',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Ответ пользователя'),
        ),
    ]
