# Generated by Django 4.2.19 on 2025-02-18 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calcul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number1', models.IntegerField(blank=True, null=True, verbose_name='Первое значение')),
                ('number2', models.IntegerField(blank=True, null=True, verbose_name='Второе значение')),
                ('number3', models.IntegerField(blank=True, null=True, verbose_name='Третье значение')),
                ('rezult', models.IntegerField(blank=True, null=True, verbose_name='Результат')),
                ('rezultUser', models.IntegerField(blank=True, null=True, verbose_name='Результат пользователя')),
                ('level', models.IntegerField(default=0, verbose_name='Уровень сложности')),
                ('count_zvezd', models.IntegerField(blank=True, null=True, verbose_name='Количество заработанных звезд')),
                ('message', models.BooleanField(default=False, verbose_name='Сообщение')),
                ('message_warning', models.BooleanField(default=False, verbose_name='Сообщение-предупреждение')),
                ('message_error', models.BooleanField(default=False, verbose_name='Сообщение-ошибка')),
                ('message_endPlay', models.CharField(max_length=50, verbose_name='Сообщение')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('age', models.CharField(max_length=250, verbose_name='Возраст')),
                ('text', models.CharField(max_length=250, verbose_name='Текст')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('prize', models.CharField(blank=True, max_length=250, null=True, verbose_name='Приз')),
                ('count_zvezd', models.IntegerField(blank=True, null=True, verbose_name='Количество звезд')),
                ('role', models.CharField(default='user', max_length=50, verbose_name='Роль')),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(default=0, max_length=250, verbose_name='Задание')),
                ('mon', models.IntegerField(default=0, verbose_name='Понедельник')),
                ('tue', models.IntegerField(default=0, verbose_name='Вторник')),
                ('wed', models.IntegerField(default=0, verbose_name='Среда')),
                ('thu', models.IntegerField(default=0, verbose_name='Четверг')),
                ('fri', models.IntegerField(default=0, verbose_name='Пятница')),
                ('sat', models.IntegerField(default=0, verbose_name='Суббота')),
                ('sun', models.IntegerField(default=0, verbose_name='Воскресенье')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Oценка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userTasks.user')),
            ],
        ),
    ]
